# On every push this script is executed, or when it's manually run
on: [workflow_dispatch] # add back push later
name: Zola Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0
        #  submodules: recursive
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # BUILD_DIR: 
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_THEMES: true
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
